### ISSUE TITLE
report a bug

### ISSUE THREAD

**Issue by liangqx-hku** [Huangzizhou/DiffIPC-data#1]
Dear author,

Thanks for sharing your amazing work！
When I try to run the case, I encountered a bug as follow: 
`[2024-06-09 11:59:13.954] [adjoint-polyfem] [info] Saving adjoint output to 
[2024-06-09 11:59:13.970] [polyfem] [error] Can't find json for State 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't find json for State 0
Aborted (core dumped)
`
So, any good advices to fix this bug, looking forward to your reply！
Best.

**Comment by Huangzizhou** [comment]
Hi,

Thanks for your appreciation! This error suggests that the simulation JSON file cannot be found ("State" often refers to the simulation in PolyFEM). In the optimization JSON file, there's a block that specifies the paths to the simulation files:
```
    "states": [
        {
            "path": "run.json"
        }
    ],
```
Which example are you running? I can double-check if there is any missing file.

**Comment by liangqx-hku** [comment]
Hi,

Thanks for your reply!
I tried the case fig1_... and fig14..., following your provided command with two different workstation.
Thx.

________________________________

**Comment by Huangzizhou** [comment]
Hi,

I think the issue is that you need to run the command from the example folder that stores the JSON files you want to use. In `opt.json`, it points to `run.json` and expects that this file is at the current path. 

Please let me know if you have further questions.

**Comment by liangqx-hku** [comment]
Many thx! It works well now.

On 10 Jun 2024, at 23:32, zizhou ***@***.***> wrote:

﻿

This is an external email.

Hi,

I think the issue is that you need to run the command from the example folder that stores the JSON files you want to use. In opt.json, it points to run.json and expects that this file is at the current path.

Please let me know if you have further questions.
