### ISSUE TITLE
a bug about import Python binding of PolyFEM: "polyfempy.cpython-39-x86_64-linux-gnu.so: undefined symbol: zpotrf"

### ISSUE THREAD

**Issue by XuAdventurer** [Huangzizhou/DiffIPC-data#2]
Dear author,
Thanks for sharing your amazing work！

I have successfully installed polyfempy-0.7
![image](https://github.com/user-attachments/assets/b2df7e10-97ad-4e22-9241-81b19254d0d5)
But when “import polyfempy as pf", I encountered a bug "polyfempy.cpython-39-x86_64-linux-gnu.so: undefined symbol: zpotrf"
![image](https://github.com/user-attachments/assets/2366e0f3-35d9-49ec-a610-c2cdaa296a13)

**Comment by Huangzizhou** [comment]
Hi,

Thanks for your report! `zpotr` seems to be part of lapack, you might need to install lapack first. A quick try is to install the lapack and blas first. Otherwise, could you try to compile the C++ code [polyfem](https://github.com/polyfem/polyfem) to see if they work? Upon successful compilation, you can run the unit tests by just
```
./build/tests/unit_tests
```

**Comment by XuAdventurer** [comment]
Thank for your reply！
I have installed the lapack and blas by using “conda install”
![image](https://github.com/user-attachments/assets/1dee8aee-3245-488d-a2d7-8b2a6ce11c8b)
![image](https://github.com/user-attachments/assets/f6452411-aabc-4359-811a-7394cc0081c4)
and I have compiled the C++ code polyfem. I run the unit tests ,it seems work well.
![image](https://github.com/user-attachments/assets/51db4697-8aa4-4399-b0f0-566d50dc2cef)
and I also use it to run the json code,it seems no problem.
![image](https://github.com/user-attachments/assets/d029f763-97d0-406d-9bcf-61187efd98df)
However,when “import polyfempy as pf", I still encounter the bug "polyfempy.cpython-39-x86_64-linux-gnu.so: undefined symbol: zpotrf"

**Comment by Huangzizhou** [comment]
Could you please try to compile and run unit test on the [branch](https://github.com/polyfem/polyfem/tree/diffIPC) that I use for the python binding as well? And could you provide your computer system and version?

**Comment by XuAdventurer** [comment]
Thank for your reply ! !
Yes，the above result(run unit test and run json code) is based your [branch](https://github.com/polyfem/polyfem/tree/diffIPC).
This is my  computer system：
![image](https://github.com/user-attachments/assets/189b4e7e-9cec-448c-b564-37638d4e75cf)
and my python version is 3.8.19

**Comment by Huangzizhou** [comment]
Updated instructions in [github repo](https://github.com/Huangzizhou/polyfem-python) and fixed the import issue.
